services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bot-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin # Опционально
      MONGO_INITDB_ROOT_PASSWORD: password # Опционально
    networks:
      - bot-network

  bot:
    build: . # Путь к Dockerfile вашего бота
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    volumes:
      - data_dir:/app/storage
      - scripts_dir:/app/scripts
      - config_dir:/app/config
      - media_dir:/app/media
    depends_on:
      - redis
      - mongo
    networks:
      - bot-network

volumes:
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./redis_data
  mongo_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mongo_data
  media_dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./media
  data_dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  scripts_dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./e2e/scripts
  config_dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./e2e/config

networks:
  bot-network:
    driver: bridge
