bot:
  mode: "polling"
  debug: true
  admin: 7337303205 # в виде числа

cache:
  type: "redis" #redis
  redis:
    address: "redis:6379"
    password: ""
    db: 0

storage:
  type: "mongo" #mongo
  file:
    path: "./e2e/storage"
  mongo:
    address: "mongo:27017"
    login: "admin"
    password: "password"
    db: "bot_db"

media:
  type: "local"

api:
  address: ":8080"
  endpoints:
    - path: "/webhook"
      method: "POST"
      scheme: "webhook_schema"
      script: "api/webhook.lua"
    - path: "/user/{id}"
      method: "GET"
      script: "api/get_user.lua"
  schemes:
    - name: "webhook_schema"
      fields:
        - name: "event"
          type: "string"
          required: true
          source: "body"
        - name: "user_id"
          type: "number"
          required: false
          source: "body"

#secrets:
#  - name: "api_key"
#  - name: "db_password"

commands:
  - name: "start"
    description: "Начать работу с ботом"
    script: "commands/start"

  - name: "test_storage"
    description: "Тестирование хранилища"
    script: "commands/test_storage"

  - name: "test_cache"
    description: "Тестирование кеша"
    script: "commands/test_cache"

  - name: "test_http"
    description: "Тестирование HTTP"
    script: "commands/test_http"

  - name: "menu"
    description: "меню"
    keyboard: "main_menu"

  - name: "profile"
    description: "Мой профиль"
    form: "profile_form"

  - name: "search"
    description: "Поиск пользователей"
    keyboard: "search_keyboard"

keyboards:
  - name: "main_menu"
    message: "Выберите действие:"
    buttons:
      - row:
          - text: "📊 Тест Storage"
            data: "test_storage"
            script: "commands/test_storage"
          - text: "💾 Тест Cache"
            data: "test_cache"
            script: "commands/test_cache"
      - row:
          - text: "🌐 Тест HTTP"
            data: "test_http"
            script: "commands/test_http"
          - text: "👤 Профиль"
            data: "profile"

  - name: "search_keyboard"
    message: "Параметры поиска:"
    buttons:
      - row:
          - text: "По имени"
            script: "search_by_name"
          - text: "По городу"
            script: "search_by_city"
      - row:
          - text: "Активные"
            data: "search_active"
          - text: "Все"
            data: "search_all"

forms:
  - name: "profile_form"
    description: "Заполнение профиля"
    stages:
      - field: "name"
        message: "Введите ваше имя:"
        validation:
          type: "string"
          min_length: 2
          max_length: 50

      - field: "age"
        message: "Введите ваш возраст:"
        validation:
          type: "number"
          min: 14
          max: 120

      - field: "bio"
        message: "Расскажите о себе (необязательно):"
        validation:
          type: "string"
          max_length: 500
          required: false

    script: "save_profile"

#interceptors:
#  - affects: "all"
#    modules:
#      - "track_user"
#    scripts:
#      - "interceptors/log_all.lua"
#
#  - affects: "commands"
#    scripts:
#      - "interceptors/check_permissions.lua"
#
#  - affects: "text"
#    scripts:
#      - "interceptors/spam_filter.lua"

modules:
  - name: "track_user"
    cfg:
      collection: "user_activity"
      ttl: "86400"
