bot:
  mode: "polling"
  debug: true

# api
api:
  address: "localhost:8081"
  endpoints:
    - path: "/test-get"
      method: "GET"
      script: "api_test.lua"
    - path: "/test"
      method: "POST"
      scheme: "scheme_1"
      script: "api_test.lua"
  schemes:
    - name: "scheme_null"
    - name: "scheme_1"
      fields:
        - name: "user_id"
          type: "string"
          required: true
          source: "body"
        - name: "message"
          type: "string"
          required: true
          source: "body"

# сторонние сервисы
cache:
  type: "memory" # или "redis"

storage:
  type: "file" # или "mongo"
  file:
    path: "./data"
