bot:
  mode: "polling"

commands:
  - name: "start"
    description: "Приветствие"
    script: "welcome.lua"
  - name: "menu"
    description: "тест меню"
    keyboard: "main_menu"
  - name: "menu2"
    description: "тест меню"
    script: "keyboard_second_menu.lua"
  - name: "sosal"
    description: "тест меню"
    reply: "sosal"

#создание клавиатур
keyboards:
  - name: "main_menu"
    message: "main"
    buttons:
      - row:
          - name: "btn1"
            text: "Кнопка 1"
            script: "btn1_handler.lua"
          - name: "btn2"
            text: "Кнопка 2"
            data: "customData btn2"
            script: "btn2_handler.lua"
      - row:
          - name: "btn3"
            text: "Кнопка 3"
            script: "btn3_handler.lua"
          - name: "btn4"
            text: "Кнопка 4"
            data: "customData btn4"


#обработка последовательных вопросов к пользователю
forms:
  - name: "form1"
    stages:
      - name: "first stage"
        output: "введите имя" #msg or script/keyboard
        input: "user_name"
      - name: "btn stages"
        output: 
          keyboard: "some_keyboard"
    output:
      - val: "user_name"
        type: string
      - val: "user_old"
        type: int

#входные и выходные интеграции
integrations:
  in:
    - name: ""
      data: 
        - val: ""
          type: 
      handler: ""
  out:

  
