bot:
  mode: "polling"

storage:
  type: "file" # или "mongo"
  file:
    path: "./data"
  mongo:
    uri: "mongodb://localhost:27017"
    db: "appdb"

http:
  address: ":8080"
  endpoints:
    - path: "/test-get"
      method: "GET"
      scheme: "scheme_null"
      script: "api_test.lua"
    - path: "/test"
      method: "POST"
      scheme: "scheme_1"
      script: "api_test.lua"
  schemes:
  - name: "scheme_null"
  - name: "scheme_1"
    fields:
      - name: "user_id"
        type: "string"
        required: true
        source: "body"
      - name: "message"
        type: "string"
        required: true
        source: "body"
      - name: "X-Request-Id"
        type: "string"
        required: false
        source: "header"
  
commands:
  - name: "start"
    description: "Приветствие"
    script: "welcome.lua"
  - name: "menu"
    description: "тест меню"
    keyboard: "main_menu"
  - name: "menu2"
    description: "тест меню"
    script: "keyboard_second_menu.lua"
  - name: "sosal"
    description: "тест меню"
    reply: "sosal"
  - name: "register"
    form: "user_registration"

forms:
  - name: "user_registration"
    description: "Регистрация пользователя"
    stages:
      - field: "user_name"
        message: "Введите ваше имя:"
        validation:
          type: "string"
          min_length: 2
      - field: "user_age"
        message: "Выберите возрастную группу:"
        keyboard: "age_groups"
      - field: "user_email"
        message: "Введите ваш email:"
        validation:
          type: "email"
      - field: "newsletter"
        message: "Подписаться на рассылку?"
        keyboard: "yes_no"
    script: "user_regestration.lua"

#создание клавиатур
keyboards:
  - name: "main_menu"
    message: "main"
    buttons:
      - row:
          - name: "btn1"
            text: "Кнопка 1"
            script: "btn1_handler.lua"
          - name: "btn2"
            text: "Кнопка 2"
            data: "customData btn2"
            script: "data_save_test.lua"
      - row:
          - name: "btn3"
            text: "Кнопка 3"
            script: "btn3_handler.lua"
          - name: "btn4"
            text: "Кнопка 4"
            data: "customData btn4"
  - name: "age_groups"
    message: "Выберите возраст:"
    buttons:
      - row:
          - name: "18-25"
            data: "18-25"
            text: "18-25 лет"
          - name: "26-35"
            data: "26-35"
            text: "26-35 лет"
  - name: "yes_no"
    message: "Подтвердите выбор:"
    buttons:
      - row:
          - name: "yes"
            text: "Да"
          - name: "no"
            text: "Нет"

    