# приоритет в обработке сообщения: форма -> роль-фильтр -> interceptors -> обработка
bot:
  mode: "polling"
  allow_group: true
  is_admin: false #админ группы, бот без имени постит там вот это все
  debug: true
  channel: "@myChannel"

# секреты (регистрация новых env переменных)
# можно ревилить в луа скриптах например для хранения апи токенов
# все зареганые секреты обязательны
secrets:
#  - name: "API_TOKEN"

# media
media:
  type: "local" # яндекс дикс, гугл диск, s3 minio?

# api
api:
  address: ":8082"
  endpoints:
    - path: "/test-get"
      method: "GET"
      scheme: "scheme_null"
      script: "api_test"
    - path: "/test"
      method: "POST"
      scheme: "scheme_1"
      script: "api_test"
  schemes:
    - name: "scheme_null"
    - name: "scheme_1"
      fields:
        - name: "user_id"
          type: "string"
          required: true
          source: "body"
        - name: "message"
          type: "string"
          required: true
          source: "body"
        - name: "X-Request-Id"
          type: "string"
          required: false
          source: "header"

# сторонние сервисы
cache:
  type: "memory" # или "redis"
  redis:
    address: "redis:6379"
    password: "REDIS_PWD"
    db: 0

storage:
  type: "file" # или "mongo"
  file:
    path: "./data"
  mongo:
    address: "mongo:27017"
    login: "admin"
    password: "MONGO_PWD"
    db: "appdb"

# Запускаются прежде всего
interceptors:
  - affects: "all" #all, commands, text, buttons, media(img,file),regex, url, filter(add filepath)
    scripts:
      - "middleware"
    modules:
      - "track_user" # save_user, log, idk...
  - affects: "all" #all, commands, text, buttons, media(img,file),regex, url, filter(add filepath)
    modules:
      - "track_user" # save_user, log, idk...

#возможность переключиться на пользовательский режим хранение в ключе кэша
commands:
  - name: "start"
    description: "Приветствие"
    script: "welcome"
    role: "all" #admin, <roleName>,<roleName> table is admins anyway [name - role] use redis aka db
    use: "private" #group channel
  - name: "menu"
    description: "тест меню"
    keyboard: "main_menu"
    role: "admin" # придумать отбивку
    use: "private" #group channel
  - name: "menu2"
    description: "тест меню"
    script: "keyboard_second_menu"
    use: "private" #group channel
  - name: "sosal"
    description: "тест меню"
    reply: "sosal"
    use: "private" #group channel
  - name: "register"
    form: "user_registration"
    use: "private" #group channel
  - name: "photo"
    form: "photo_test"
    use: "private" #group channel

#сделать ролевое ограничение, роли зашивать как тг логины в env

#настройка модулей
modules:
  - name: "save_user"
    cfg:
      table: "customers"

#добавить формы через миниапп

#формы не работают в общем чате
#todo пересылка в лс при попытке вызвать форму в общем чате
forms:
  - name: "user_registration"
    description: "Регистрация пользователя"
    stages:
      - field: "user_name"
        message: "Введите ваше имя:"
        validation:
          type: "string"
          min_length: 2

      - field: "user_age"
        message: "Выберите возрастную группу:"
        keyboard: "age_groups"

      - field: "user_email"
        message: "Введите ваш email:"
        validation:
          type: "email"

      - field: "newsletter"
        message: "Подписаться на рассылку?"
        keyboard: "yes_no"

    script: "user_regestration"

  - name: "photo_test"
    description: "тест работы с фото"
    stages:
      - field: "photo"
        message: "пришлите фото"
        validation:
          type: "photo"

    script: "photo"

#todo Переделать на редактирование сообщения вместо удаления
#создание клавиатур
keyboards:
  - name: "main_menu"
    message: "main"
    buttons:
      - row:
          - text: "Кнопка 1"
            script: "btn1_handler"
          - text: "Кнопка 2"
            data: "customData btn2"
            script: "data_save_test"
      - row:
          - text: "Кнопка 3"
            script: "btn3_handler"
          - text: "Кнопка 4"
            data: "customData btn4"

  - name: "age_groups"
    message: "Выберите возраст:"
    buttons:
      - row:
          - text: "18-25 лет"
            data: "18-25"
          - text: "26-35 лет"
            data: "26-35"

  - name: "yes_no"
    message: "Подтвердите выбор:"
    buttons:
      - row:
          - text: "да"
            data: "yes"
          - text: "нет"
            data: "no"
